cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br # Configurando CORS de forma global
file:
  upload-dir: /JAVA_UPLOAD_DIR/UploadDir
security:
  jwt:
    token:
      secret-key: mySecretKey53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot
    username: postgres
    password: admin123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none # None significa que o hibernate só vai ler e gravar no BD e o Update ele irá mudar a estrutura do banco
    properties:
      hibernate:
        show_sql: false # Quando tiver debugando use como true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  flyway:
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot
    user: postgres
    password: admin123
    schemas: public
springdoc:
  pathsToMatch:
    - /auth/**/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true