name: Continuous Integration with Github Actions

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
    - uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 21
    - uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
  
    - name: Build Application JAR
      working-directory: ./22_DockerizingOurApp/rest-with-spring-boot-and-java
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./22_DockerizingOurApp
      run: docker compose -up -d --build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot:latest ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot:latest
        
